can_to_gazebo:
  ros__parameters:
    motors:
      - can_id: 1
        joint_name: wheel0_motor_shaft_joint
        invert: false
        control_type: velocity

      - can_id: 2
        joint_name: wheel1_motor_shaft_joint
        invert: false
        control_type: velocity

      - can_id: 3
        joint_name: wheel2_motor_shaft_joint
        invert: false
        control_type: velocity

      - can_id: 4
        joint_name: wheel3_motor_shaft_joint
        invert: false
        control_type: velocity
