controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    # センサーの値を/joint_statesに返すコントローラー
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    # 指示値をモーター(joint)に送るコントローラー
    forward_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController


# ============================================================
# コントローラの設定
# joints の順番は motors 設定の順番と一致させてください
# ============================================================
forward_velocity_controller:
  ros__parameters:
    joints:
      - wheel_left_joint
      - wheel_right_joint